name: "Deploy on Vercel"

on:
  workflow_call:
    secrets: 
      GH_TOKEN:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_PROJECT_ID:
        required: true
      VERCEL_ORG_ID:
        required: true
    inputs:
      production:
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.head_commit.message, '[skip ci]')}}
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel
        uses: org013/deploy-to-vercel-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}